travis:
  secure:
    BINSTAR_TOKEN: XlmSIzaHcA+lsX7+1PYdC7G1pW1gh35pkozmsnnMbVazaU9h7EDeA7N1BgyKDljoQW8zO9R0y+Q4tGEFUKGQPDKvcYUuVjhUJXR9O0e1V5LPgks4+htu/L1uxwbHLIdz0067baA95tBy+ybJn97kbTFCcjQV/VwYVMqwq50MxTtLeqfAVz/LuZJXNt580YsuUoMWc7/2Ia/agDTarpgjsPZzD/rCR0yPXgjrv4BHgLdrNbRyC2E51TJAKpzVvNj1YlaJxgZ/Lt5jJOpo7I5Mg52IGjL8z1ZTBtpYUWV6V25mAVlmvfME7YA59TTzZMRLKICz2nTuKNOdLKnE/HWzmgN66FJAR50KAEad3h1fdtj1+MXKaGLhLb33i4ocatL8OaASECfeef2iOlGzVuvBivuXWbKHofXl3YN13GUCBya+pE+EtXaY/wQXUQhchw0P6MOCb/K+DmZXRsy3k1rvknakV2nvXzOYNA+tlADrhqKZLqD1TCZMkXIWRZ6u2BDgF6uJU96Nw8v2zmvi5/ivhrbG8a7MpHn0QpuY1jUCUG69mj3/0J3IGhQNVlSX67y8DdZ2Ua31kwbSLMn5B5v6SZRNVQ73jfZQjVh7EGss0ZzRK2YQxGdNhTqHdbcz3iT7I4nN3qrKzvUDTNT2IcBt+iXhwfi1w5vatnlufxHRQUc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
