travis:
  secure:
    BINSTAR_TOKEN: CSRopUpqQEssV4L1vGWrcoAlySh9967fHG/ytDw2EsqLxCreVko40/TmmNGZKuCO6gul6AxyUetVWzzcqNDwm9mgtA3Zz4APrN2dz9TvemXR+yJ3pb0X/VWzmH5ENMxr9Zi8D7DyesGCRjh1Q4IqsIipnIjLga1Am61PERvgcJm3ijbonkrdzowXQk/wbUYD29s9apGfLItLb6gn4F1moxCyJ74weMAjdr6u2Xh6e/GEnyPj6SM3HSgqIdvqbfhX+t/i6CEiFAYfjGhxxEXDgdzunOEDzr0K+ejJYCHX+038fvP4W0uF+P2w5y3rtSHtogHGySQy/J+gpeckmDNiuGvVqlB6d2tlqn4wMebogLiJKiO3WKEDaMeVDLZhLljDYNkkxDS8QqTUgA8sYwmcZB+pVmngsF1LQXLrOYH1Il1Vw21Uocg2XoVdqupLRrGOKGAdTyXnhE840O0iB0ErmrJVcWX2LfQnUgcaMpJv9SVJqi9TosoVDzsXp172//sqH5XaAEmTCB2etDfcAu7A1L01/hnZHxMdlXNTDVAoWPtaIadfNGJJCBFrp37hLlMSdoDDO5NyhHAqyjdAdps9BH1l2ugxKRfSb9gi0MXLSxSJFr0dWFTKHbfiHSPL6h549kiXckCg9EQMytR8RtLSPErX18X+yXPoXvZP1quOpAI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
