appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dw7aWH8Hb3Up+vQMyzA+VHaygA1pFJQmp9EE2UmEIm+QeXcd1Ejyo/kOsgFODA1/NTrX6+98NR3meWjjba88ydi3PAg1VwVCxbC1xSOdvaaSxp6fL5vUdR/Cu1+1TqyTr0rK2LFp/u21s9M6q9HIKWj57mlL3YPWPN89QgvqOHGVmWgJFnhgF9QgU+khoceUnJdp5neBmQRkwY+K9TION4ZxKRvpV/WMIiH8dsGXa3hhb5aIuSNlzghgVQ/IQta8nIK63rNV2C3/uGdeqooyMkx64g92yMLhp2rY19x5JMEQ5fPnzbjKMKAIUCUlImpQMiBMR8F+1McKwUV/LFUn0I+cg4DBVzaB0Rxk4GF425uGPZHU1BgA93sDZrRU9HVtyrBxrxEcSSeSUaPUdOWV0QAIWZPuIZNMPoilkGt9kRv4yr92TZsHDdWlioxv93aHkcrxiWnjU0f/rheL8QmtRL1KJ6MYB9NksUdaFAmcFqhlzEvS4hwnAeEPe1+mxN8a7JeDrEtbRbNI2KY3xQltm/iYBDmHKkn4V6cHPrT6jx2vu/rSX+XyuI8w/nKksKf2GK3RxlTpFnSxOgmd/Z1kshpRjJlhajzOlWz9Ea0hizoPmrjIdDDf74Ud0dGfeO47KeQw4qRMwnjxNsUYmJf+CHzDfyFMmRXJkIBD5Fo8iE4=}
conda_forge_output_validation: true
